[package]
name = "pphysx3d"
version = "0.1.0"
authors = ["Isak Larsson, Axel Lervik, Arian Hanifi, Malte Blomqvist"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = "0.30.0"

